# Generated by Django 4.2.1 on 2023-05-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='wallet',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Сума акаунта'),
        ),
    ]
