# Generated by Django 4.2.1 on 2023-05-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
                ('name', models.CharField(max_length=225, null=True, verbose_name='Назва кредиту')),
                ('percent', models.IntegerField(null=True, verbose_name='Процент множення кредиту')),
                ('credit_length', models.IntegerField(verbose_name='Кількість необхідних оплат')),
                ('payed_times', models.IntegerField(default=0, verbose_name='Кількість теперішніх оплат')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
            ],
            options={
                'verbose_name': 'Кредит',
                'verbose_name_plural': 'Кредити',
            },
        ),
        migrations.CreateModel(
            name='Deposits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
                ('name', models.CharField(max_length=225, null=True, verbose_name='Назва депозиту')),
                ('percent', models.IntegerField(null=True, verbose_name='Процент множення депозиту')),
                ('deposit_length', models.IntegerField(verbose_name='Кількість виплат')),
                ('payed_times', models.IntegerField(default=0, verbose_name='Кількість теперішніх оплат')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
            ],
            options={
                'verbose_name': 'Депозит',
                'verbose_name_plural': 'Депозити',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('food', 'Їжа'), ('shopping', 'Шопінг'), ('trip', 'Подорож'), ('education', 'Навчання'), ('accrual', 'Нарахування'), ('restaurant', 'Ресторани'), ('alcohol', 'Алкоголь'), ('health', 'Здоровя'), ('services', 'Послуги'), ('others', 'Інше')], max_length=16, null=True, verbose_name='Категорія транзакції')),
                ('status', models.CharField(choices=[('income', 'Дохід'), ('expense', 'Витрата')], max_length=16, null=True, verbose_name='Статус транзакції')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Сума')),
            ],
            options={
                'verbose_name': 'Транзакція',
                'verbose_name_plural': 'Транзакції',
            },
        ),
    ]
