# Generated by Django 4.2.1 on 2023-05-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credits',
            name='payed_times',
            field=models.IntegerField(default=0, verbose_name='Кількість теперішніх оплат'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='category',
            field=models.CharField(choices=[('food', 'Їжа'), ('shopping', 'Шопінг'), ('trip', 'Подорож'), ('education', 'Навчання'), ('accrual', 'Нарахування'), ('restaurant', 'Ресторани'), ('alcohol', 'Алкоголь'), ('health', 'Здоровя'), ('services', 'Послуги'), ('others', 'Інше')], max_length=16, null=True, verbose_name='Категорія транзакції'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
