# Generated by Django 4.2.1 on 2023-05-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_credits_payed_times_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposits',
            name='deposit_length',
            field=models.IntegerField(verbose_name='Кількість виплат'),
        ),
        migrations.AlterField(
            model_name='deposits',
            name='payed_times',
            field=models.IntegerField(default=0, verbose_name='Кількість теперішніх оплат'),
        ),
    ]
